/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacfc.src.views;

import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sistemacfc.src.control.AgendaControl;

/**
 *
 * @author Indiara
 */
public class TelaAgendamento extends javax.swing.JFrame {

    private AgendaControl control;

    public TelaAgendamento(AgendaControl ctrl) {
        this.control = ctrl;
        initComponents();
    }

    public JTextField getInstrutorCarro() {
        return instrutorCarro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        provas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProva = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tipoProva = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cpfProva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alunoProva = new javax.swing.JTextField();
        agendarProva = new javax.swing.JButton();
        praticas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePraticas = new javax.swing.JTable();
        cpfPratica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alunoPratica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        instrutorCarro = new javax.swing.JTextField();
        agendarPratica = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tipoCarro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        placaCarro = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        teoricas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("A G E N D A");

        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        provas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tabelProva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelProva);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo da prova");

        tipoProva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoProva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<selecionar>", "Teórica", "Prática" }));
        tipoProva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoProvaItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Aluno");

        cpfProva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfProva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpfProvaKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nome");

        alunoProva.setEditable(false);
        alunoProva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        agendarProva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agendarProva.setText("Agendar");
        agendarProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarProvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout provasLayout = new javax.swing.GroupLayout(provas);
        provas.setLayout(provasLayout);
        provasLayout.setHorizontalGroup(
            provasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, provasLayout.createSequentialGroup()
                .addGroup(provasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(provasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(provasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(provasLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoProva, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(cpfProva, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(alunoProva, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(provasLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(agendarProva, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
        provasLayout.setVerticalGroup(
            provasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(provasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(provasLayout.createSequentialGroup()
                        .addGroup(provasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tipoProva, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfProva, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alunoProva, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agendarProva, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Provas", null, provas, "Agendamento de provas teóricas e práticas\n");

        tablePraticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablePraticas.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(tablePraticas);

        cpfPratica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfPratica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfPraticaActionPerformed(evt);
            }
        });
        cpfPratica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpfPraticaKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Aluno");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nome");

        alunoPratica.setEditable(false);
        alunoPratica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Instrutor");

        instrutorCarro.setEditable(false);
        instrutorCarro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instrutorCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instrutorCarroActionPerformed(evt);
            }
        });

        agendarPratica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agendarPratica.setText("Agendar");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tipo do Carro");

        tipoCarro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<selecionar>", "A", "B", "C", "D", "E", "Reciclagem" }));
        tipoCarro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoCarroItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Placa");

        placaCarro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        placaCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<selecionar>", "Teórica", "Prática" }));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Aulas realizadas");

        javax.swing.GroupLayout praticasLayout = new javax.swing.GroupLayout(praticas);
        praticas.setLayout(praticasLayout);
        praticasLayout.setHorizontalGroup(
            praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, praticasLayout.createSequentialGroup()
                .addGroup(praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(praticasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, praticasLayout.createSequentialGroup()
                                    .addComponent(cpfPratica, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(alunoPratica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(praticasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instrutorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(praticasLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(praticasLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(agendarPratica, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(praticasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(placaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(praticasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
        praticasLayout.setVerticalGroup(
            praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(praticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(praticasLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpfPratica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alunoPratica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(praticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(placaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instrutorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(agendarPratica, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Aulas Práticas", null, praticas, "Agendamento de aulas teóricas incluindo reposições");

        teoricas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1234", "Aula 5", "Matutino", "24/04/17"},
                {"4321", "Aula 5", "Matutino", "26/04/17"},
                {"2468", "Aula 5", "Vespertino", "24/04/17"}
            },
            new String [] {
                "Turma", "Aula", "Periodo", "Data"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Aluno");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setText("Indiara Camillo Menegat");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nome");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Aula(s) faltante(s)");

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setText("Aula 5");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("<html><center>Lista de turmas onde serão ministradas<br> as aulas faltantes");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Agendar");

        javax.swing.GroupLayout teoricasLayout = new javax.swing.GroupLayout(teoricas);
        teoricas.setLayout(teoricasLayout);
        teoricasLayout.setHorizontalGroup(
            teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teoricasLayout.createSequentialGroup()
                .addGroup(teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teoricasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(teoricasLayout.createSequentialGroup()
                                .addGroup(teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(teoricasLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField8))))
                        .addGap(5, 5, 5))
                    .addGroup(teoricasLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teoricasLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        teoricasLayout.setVerticalGroup(
            teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teoricasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teoricasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addGroup(teoricasLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(teoricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );

        jTabbedPane1.addTab("Aulas Teóricas", null, teoricas, "Agendamento de reposição de aulas teóricas em outras turmas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void instrutorCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instrutorCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instrutorCarroActionPerformed

    private void cpfPraticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfPraticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfPraticaActionPerformed

    private void tipoProvaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoProvaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                String tipo = tipoProva.getSelectedItem().toString();
                tabelProva.setModel(control.exibirProvas(tipo));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tipoProvaItemStateChanged

    private void cpfProvaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfProvaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                alunoProva.setText(control.verificarCPF(cpfProva.getText()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cpfProvaKeyPressed

    private void agendarProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarProvaActionPerformed
        if (evt.getActionCommand().equals(agendarProva.getActionCommand())) {
            int reply = JOptionPane.showConfirmDialog(this, "Deseja mesmo agendar essa data para o aluno?", "Agendamento", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                String cpf = cpfProva.getText();
                String data = tabelProva.getValueAt(tabelProva.getSelectedRow(), 0).toString();
                try {
                    control.agendarProva(cpf, data);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_agendarProvaActionPerformed

    private void cpfPraticaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfPraticaKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           String cpf = cpfPratica.getText();
           try {
               alunoPratica.setText(control.getPrincipal().exibirNomeAluno(cpf));
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_cpfPraticaKeyPressed

    private void tipoCarroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoCarroItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
           String cpf = cpfPratica.getText();
            try {
                placaCarro.setModel((DefaultComboBoxModel) control.exibirInfosTela(cpf));
            } catch (SQLException ex) {
                Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }//GEN-LAST:event_tipoCarroItemStateChanged

    
    public JTextField getInstrutor() {
        return instrutorCarro;
    }

    public JComboBox<String> getPlacaCarro() {
        return placaCarro;
    }

       public JComboBox<String> getTipoCarro() {
        return tipoCarro;
    }
    
       public javax.swing.JTable getTableProvas(){
           return tabelProva;
       }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendarPratica;
    private javax.swing.JButton agendarProva;
    private javax.swing.JTextField alunoPratica;
    private javax.swing.JTextField alunoProva;
    private javax.swing.JTextField cpfPratica;
    private javax.swing.JTextField cpfProva;
    private javax.swing.JTextField instrutorCarro;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox<String> placaCarro;
    private javax.swing.JPanel praticas;
    private javax.swing.JPanel provas;
    private javax.swing.JTable tabelProva;
    private javax.swing.JTable tablePraticas;
    private javax.swing.JPanel teoricas;
    private javax.swing.JComboBox<String> tipoCarro;
    private javax.swing.JComboBox<String> tipoProva;
    // End of variables declaration//GEN-END:variables
}
